# SPDX-License-Identifier: GPL-2.0-only
PACKAGE_NAME="gc573_pure"
PACKAGE_VERSION="0.1.0~beta1"

BUILT_MODULE_NAME[0]="gc573_pure"
BUILT_MODULE_LOCATION[0]="src"
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make -C src KDIR=/lib/modules/${kernelver}/build"
CLEAN[0]="make -C src clean KDIR=/lib/modules/${kernelver}/build"

# Rebuild/install this module for kernels managed by DKMS.
AUTOINSTALL="yes"
